name: Build and publish ASP.NET Core on Azure App Service (Blue/Green)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:    
  DOTNET_VERSION: '5.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    
    - uses: azure/login@v1
      name: 'Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: dotnet restore
      run: dotnet restore   
      working-directory: ./AppServiceReleaseStrategy 
  
    - name: dotnet build
      run: dotnet build --configuration Release
      working-directory: ./AppServiceReleaseStrategy 
    
    - name: dotnet publish
      run:  dotnet publish -c Release -o './myapp' /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}
      working-directory: ./AppServiceReleaseStrategy 
                   
    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'serverlessday2021onappservice' 
        package: './AppServiceReleaseStrategy/myapp/'
        slot-name: 'green'

  swap:
    runs-on: ubuntu-latest
    needs: [ build-and-deploy ]
    steps:

    - uses: azure/login@v1
      name: 'Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Swap to production
      uses: Azure/cli@1.0.4
      with:
        inlineScript: az webapp deployment slot swap --name serverlessday2021onappservice --resource-group 'RG-SERVERLESS-DAY-2021' --slot green --target-slot production
